[package]
name = "render-dom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-dom = {path = "../html-dom"}
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"

